export const PDF_COLORS = {
  primary: "#C53030",
  primaryLight: "#FED7D7",
  primaryDark: "#9B2C2C",
  textPrimary: "#1A202C",
  textSecondary: "#4A5568",
  textMuted: "#718096",
  textLight: "#A0AEC0",
  bgWhite: "#FFFFFF",
  bgLight: "#F7FAFC",
  bgMid: "#EDF2F7",
  bgAccent: "#FFF5F5",
  tableHeader: "#2D3748",
  tableHeaderTx: "#FFFFFF",
  tableRowAlt: "#F7FAFC",
  tableBorder: "#E2E8F0",
  tableRowHover: "#EBF8FF",
  green: "#276749",
  greenLight: "#C6F6D5",
  amber: "#B7791F",
  amberLight: "#FEFCBF",
  red: "#C53030",
  redLight: "#FED7D7",
  blue: "#2B6CB0",
  blueLight: "#BEE3F8",
  gray: "#4A5568",
  grayLight: "#EDF2F7",
} as const;

export const PDF_FONTS = {
  heading: "helvetica",
  body: "helvetica",
  mono: "courier",
} as const;

export const PDF_SIZES = {
  pageW: 210,
  pageH: 297,
  marginLeft: 14,
  marginRight: 14,
  marginTop: 12,
  marginBottom: 18,
  contentW: 182,
  fontH1: 18,
  fontH2: 13,
  fontH3: 11,
  fontBody: 9,
  fontSmall: 8,
  fontTiny: 7,
  spaceSM: 3,
  spaceMD: 6,
  spaceLG: 10,
  spaceXL: 16,
  tableHeaderH: 8,
  tableRowH: 7,
  tablePadX: 3,
  tablePadY: 2,
} as const;

export const PDF_META = {
  creator: "FRMT Centre National — CNE V2",
  author: "Fédération Royale Marocaine de Tennis de Table",
  subject: "Document officiel FRMT",
} as const;
